Base elements:
 - Sup
 - Table / Empty
 - Table
Components:
 - Side navigation / Docs
 - Side navigation / Expandable dark
 - Side navigation / Expandable
 - Side navigation / With icons
 - Side navigation / Raw HTML
 - Side navigation / Sticky
 - Slider / Input
 - Status labels / Default
 - Strip / Accent
 - Strip / Deep
 - Strip / Image
 - Tooltips
 - Tooltips / Detached
 - Extra small capitalised text
 - Utilities
 - Padding collapse
 - Show
 - Table cell padding overlap
 - Truncate text
 - Vertical spacing
 - Vertically center
 - Layouts
 - Application / JAAS
 - Application / Default
Templates:
 - MAAS docs / Grid layout
 - MAAS layout
 - Responsive behaviours
 - Snapcraft publicise page
